theme: jekyll-theme-minimal
logo: /images/Extra-Life-Tracker-Logo.png
description: Extra Life Tracker is a collection of web pages that can be used as a web source in streaming software such as OBS to display your and your team's current Extra Life fund raising status and goal.